/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Disk Cleanup": "硬盘清理",
    "Hard Disk is Full": "硬盘已满",
    "You have run out of space on drive C.\n\nTo free space on this drive by deleting old or unnecessary files, click Disk Cleanup.": "驱动器 C 上的空间已用完。\n\n要通过删除旧的或不需要的文件来释放此驱动器上的空间，请单击“磁盘清理”。",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Find": "查找",
    "Disk Properties": "硬盘属性",
    "Help": "帮助",
    "Install programs": "安装程序",
    "Install Programs": "安装程序",
    "Log Off": "注销",
    "Programs": "程序",
    "Shut Down...": "关机...",
    "bytes": "字节",
    "Capacity:": "容量：",
    "Disk Cleanup Utility not found.  Please remove all files from this computer manually by clicking on them and pressing delete.": "找不到磁盘清理实用程序。 请手动删除此计算机中的所有文件，方法是单击它们并按删除键。",
    "Drive Properties": "硬盘属性",
    "Free Space:": "剩余空间：",
    "OK": "确定",
    "Shrink used space to 0 to win!": "将已用空间缩小为 0 即可获胜！",
    "Used Space:": "已用空间：",
    "Windows has encountered an error": "Windows 遇到了一个错误",
    "Running Disk Cleanup...": "正在运行磁盘清理...",
    "Time remaining:": "剩余时间：",
    "My Computer": "我的电脑",
    "Open": "打开",
    "My Documents": "我的文档",
    "Downloads": "下载",
    "Delete": "删除",
    "Pictures": "我的照片",
    "Notes": "记事本",
    "Error": "错误",
    "Windows has encountered an error.": "Windows 遇到了一个错误。",
    "Confirm File Delete": "确认删除文件",
    "No": "否",
    "Yes": "是",
    "Add": "添加",
    "Add Programs": "添加程序",
    "Delete boost": "删除提升",
    "Free space:": "剩余空间：",
    "Reduce the time it takes to delete a file": "减少删除文件所需的时间",
    "Size:": "大小：",
    "You don't have enough free space": "您没有足够的可用空间",
    "Paintings": "画图",
    "Deleting": "删除",
    "KB per second": "KB每秒",
    "Photos": "照片",
    "Administrator": "管理员",
    "Research": "研究",
    "Unauthorized. You do not currently have permission to open this.": "未经授权。 您目前没有权限打开它。",
    "More deletes": "更多的删除",
    "Installed": "已安装",
    "File Access Level": "文件访问等级",
    "Delete boost Installed successfully.  Check the Start Menu or System files to use the new functionality.": "删除提升 安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "Allows navigation and deletion of protected files.  Each level gives access to more files.": "允许导航和删除受保护的文件。 每个级别都可以访问更多文件。",
    "Allows simultaneous deletion of more files. Each upgrade allows 1 more delete": "允许同时删除更多文件。 每次升级允许再删除 1 次",
    "Auto deleter count": "自动删除器计数",
    "Auto deleter count Installed successfully.  Check the Start Menu or System files to use the new functionality.": "自动删除器计数已成功安装。 检查“开始”菜单或系统文件以使用新功能。",
    "Auto deleter speed": "自动删除速度",
    "Auto deleter speed Installed successfully.  Check the Start Menu or System files to use the new functionality.": "自动删除速度 安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "Auto deletes the smallest file in the active window every 10 seconds. Each upgrade increases the amount you can have open.": "自动每 10 秒删除活动窗口中的最小文件。 每次升级都会增加您可以打开的数量。",
    "Auto deletes the smallest file in the active window every 10 seconds. Each upgrade subtracts 2 seconds from the duration.": "自动每 10 秒删除活动窗口中的最小文件。 每次升级都会从持续时间中减去 2 秒。",
    "Delete express": "删除指令",
    "Extremely reduce the time it takes to delete a file": "极大地减少删除文件所需的时间",
    "File Access Level Installed successfully.  Check the Start Menu or System files to use the new functionality.": "文件访问级别 安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "More deletes Installed successfully.  Check the Start Menu or System files to use the new functionality.": "更多删除 安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "Unauthorized. You do not currently have permission to delete this.": "未经授权。 您目前无权删除此内容。",
    "Max number of deletes open": "已达到最大同时删除文件数量",
    "Delete express Installed successfully.  Check the Start Menu or System files to use the new functionality.": "删除指令 安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "Select box": "选择框",
    "Autodeleter": "自动删除器",
    "AutoDelete": "自动删除",
    "AutoDeleter": "自动删除器",
    "Lock to window": "锁定到窗口",
    "No files to delete. Focus a window with available files to get started.": "没有要删除的文件。 聚焦一个包含可用文件的窗口以开始。",
    "Allow selection of multiple files.": "允许批量选择文件。",
    "Unlock": "解锁",
    "Max Level": "最高等级",
    "Select box Installed successfully.  Check the Start Menu or System files to use the new functionality.": "选择框安装成功。 检查“开始”菜单或系统文件以使用新功能。",
    "Games": "游戏",
    "You win!": "你赢了！",
    "Succes": "成功",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Deleting ": "删除 ",
    "searching for file in ": "搜索文件在 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)KB$/,
    /^([\d\.]+)MB$/,
    /^([\d\.]+)GB$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Are you sure you want to send (.+) to the Recycle Bin\?$/, '您确定要将 $1 发送到回收站吗？'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) minute, ([\d\.]+) seconds$/, '$1 分钟，$2 秒'],
    [/^([\d\.]+) minutes, ([\d\.]+) seconds$/, '$1 分钟，$2 秒'],
    [/^([\d\.]+) second$/, '$1 秒'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);